
<div class="col-md-6">

    <!-- general form elements disabled -->
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Post News Feed</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">

            <div class="postId"><?php echo "<b>POST ID:</b>". ((!empty($result))?$result:'')?></div>
            <form role="form" method="post" >

                <div class="form-group">
                    <label>Access Token</label>
                    <input type="text" name="form[txtToken]" class="form-control" placeholder="Enter ...">
                </div>
                <div class="form-group">
                    <label>Caption</label>
                    <input type="text" name="form[txtCaption]" class="form-control" placeholder="Enter ...">
                </div>
                <div class="form-group">
                    <label>Link Photo</label>
                    <textarea class="form-control" name="form[txtLink]" rows="3" placeholder="https://pictures/navas.jpg"></textarea>
                </div>
                <button type="submit" class="btn btn-block btn-success">Success</button>
            </form>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>