
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card " style="height: auto">
                <div class="card-header">
                    <h3 class="card-title custom-card-order">Customers</h3>
                    <button type="button" class="btn btn-block btn-outline-secondary custom-btn-add"><a href="/order/createorder"><i class="fa fa-plus-square" aria-hidden="true"></i> ADD NEW</a></button>
                </div>
                <!-- /.card-header -->
                <div class="card-body" >
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Stt</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Number Phone</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php  foreach ($result as $key=> $val) {
                            ++$key;
                            echo "<tr>
                                    <td>{$key}</td>
                                    <td><a href='/order/orderlist?id={$val['CustomerID']}'>{$val['Name']}</a></td>
                                    <td>{$val['Address']}</td>
                                    <td>{$val['NumberPhone']}</td>
                                </tr>";
                        }
                        ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Stt</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Number Phone</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->


        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->


<!--<script src="../../public/plugins/jquery/jquery.min.js"></script>-->
<script>
    $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false

        });
    });
</script>

