
<div class="list-page">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="text-align: center">Select page</h3>

        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <ul class="products-list product-list-in-card pl-2 pr-2">
                <?php foreach ($result as $value) { ?>
                    <li class="item">
                        <div class="product-img">
                            <img src="<?php echo '//graph.facebook.com/' . $value['id'] . '/picture' ?>"
                                 alt="Product Image" class="img-size-50">
                        </div>
                        <div class="product-info">
                            <a href="#" class="product-title"
                               data-convId="<?php echo $value['id'] ?>"><?php echo $value['name'] ?></a>
                        </div>
                        <button type="button" class="btn btn-success"><a href="<?php echo '/face/manage-post/listpost?PageID='.$value['id'].'&access_token='.$value['access_token']?>">Select</a></button>
                    </li>
                <?php } ?>
            </ul>
        </div>

    </div>
</div>